### ISSUE TITLE
Failed building of examples on Apple with clang compilers

### ISSUE THREAD

**Issue by BarrySmith** [trilinos/xSDKTrilinos#3]
ftp://ftp.mcs.anl.gov/pub/petsc/nightlylogs/archive/2016/04/18/configure_next_arch-osx-xsdk-opt_ipro.log 

--with-debugging=0 --download-hypre=1 --download-metis=1 --download-parmetis=1 --download-superlu_dist=1 --download-trilinos=1 --download-xsdktrilinos=1 --download-mpich=1 --with-clanguage=C++ --with-cxx-dialect=C++11 --download-sowing=1 --with-boost-dir=/usr/local --download-cmake=1 --with-no-output -PETSC_ARCH=arch-osx-xsdk-opt -PETSC_DIR=/Users/petsc/petsc.clone-4 --download-hdf5 --download-netcdf --download-exodusii

In file included from /Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/externalpackages/git.xsdktrilinos/petsc/src/BelosPETScSolMgr.cpp:44:
/Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/externalpackages/git.xsdktrilinos/petsc/src/BelosPETScSolMgr.hpp:176:34: error: allocation of incomplete type 'Epetra_Vector'
  { trilinosX = Teuchos::rcp(new Epetra_Vector(View,helper.Map(),x)); }
                                 ^~~~~~~~~~~~~
/Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Epetra_MultiVector.h:53:7: note: forward declaration of 'Epetra_Vector'
class Epetra_Vector;
      ^
1 error generated.
make[2]: **\* [petsc/src/CMakeFiles/xsdkpetsc.dir/BelosPETScSolMgr.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [petsc/src/CMakeFiles/xsdkpetsc.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
make: **\* [all] Error 2

I think there is a bug in your code but that the Gnu compilers work anyways while clang is more picky and thus generates the error. Usually "allocation of incomplete type" means that you have not included the right include file needed by C++ that defines the classes "guts" so the compiler does not have enough information to actually create the object.

**Comment by bartlettroscoe** [comment]
Just needs a simple #include "Epetra_Vector.h"

**Comment by BarrySmith** [comment]
That's easy for you to say :-)

**Comment by amklinv** [comment]
Would you mind trying the latest commit, Barry, and closing this if it fixed your issue?

PS: I did not receive an email for this issue.  Would you mind mentioning me @amklinv on future issues?

**Comment by BarrySmith** [comment]
Thanks.

   It will be in our tests.

> On Apr 19, 2016, at 2:08 PM, amklinv notifications@github.com wrote:
> 
> Would you mind trying the latest commit, Barry, and closing this if it fixed your issue?
> 
> PS: I did not receive an email for this issue. Would you mind mentioning me @amklinv on future issues?

  I think is a way for you to set it so that you are automatically informed when each new issue is posted. (Maybe "watch") Otherwise anyone else who doesn't know to put a @amklinv will get annoyed when they think you are ignoring the issue.

   Barry

**Comment by amklinv** [comment]
Ah.  I didn't realize I wasn't listed as a watcher.  I just added myself to the list.

Thanks Barry!

**Comment by bartlettroscoe** [comment]
@BarrySmith, did Alicia's commit 5b106b7 fix this issue?

**Comment by BarrySmith** [comment]
The fix seems to have resolved the issue.
