### ISSUE TITLE
xsdkhypre nightly build failure

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/xSDKTrilinos#7]
Here is what I am seeing:

[ 33%] Built target xsdkhypre
gmake[1]: Leaving directory `/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/build'In file included from /jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.cpp:44:0:
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:106:3: error: ‘RCP’ does not name a type
   RCP<const Comm> getComm() const {return comm_;};
   ^
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:109:3: error: ‘RCP’ does not name a type
   RCP<Node> getNode() const { return rowMap_->getNode(); };
   ^
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:112:3: error: ‘RCP’ does not name a type
   RCP<const Map<LO,GO,Node> > getRowMap() const { return rowMap_; };
   ^
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:115:3: error: ‘RCP’ does not name a type
   RCP<const Map<LO,GO,Node> > getColMap() const { return colMap_; };

Here are the build arguments:

sh ./installxSDK.sh --prefix=${WORKSPACE}/INSTALL_xSDK --download-trilinos-commit=origin/master --download-superlu_dist-commit=origin/master --download-hypre-commit=origin/master --download-petsc-commit=origin/master --download-alquimia-commit=origin/master

**Comment by BarrySmith** [comment]
I saw this yesterday too on Linux

**Comment by amklinv** [comment]
This looks like the issue I just fixed in the PETSc interface.  I'll fix it.

**Comment by amklinv** [comment]
Ah.  I know what went wrong.  I fixed this bug in the master branch, not in release, and the installer seems to be using the release branch of xSDKTrilinos since it's a different repository than Trilinos (and --download-trilinos-commit=origin/master probably only works for Trilinos).  Jim's going to modify the Jenkins build to use different options.

**Comment by jwillenbring** [comment]
Adding --download-xsdktrilinos-commit=origin/master caused this build to pass. Previously, I had commands to use the master branch for the other xsdk codes, but not xsdktrilinos.

**Comment by jwillenbring** [comment]
I should have closed this with the last comment.
